### ISSUE TITLE
Help file

### ISSUE THREAD

**Issue by ed-tsoy** [advancesoftcorp/espresso#1]
It would be to nice to include a short description of how to use the binary files. Should I just copy them to the source distribution of the QE? If 'yes', to what directory? How can I add GUI support, e.g PWGui? Without such a description, your binaries are not very useful, I think. Thanks.

**Comment by advancesoftcorp** [comment]
Sorry, we does not prepare binary files now. Please compile source files by yourself.
We does not support PWgui.
